name: shelf_unix_domain_socket
description: Extension library for Shelf to supports unix domain socket.
version: 1.0.3
homepage: https://github.com/kkazuo/shelf_unix_domain_socket

environment:
  sdk: '>=2.18.5 <3.0.0'

platforms:
  linux:
  macos:

dependencies:
  posix: ^4.1.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
